import { ICastlevaniaSpriteKeys } from "../types";

export const castlevaniaSprites:Record<ICastlevaniaSpriteKeys, any> = {
  Alchemy_Whip: require('../../assets/castlevania/Sprite-Alchemy_Whip.webp'),
  Alucard_Spear: require('../../assets/castlevania/Sprite-Alucard_Spear.webp'),
  Alucart_Sworb: require('../../assets/castlevania/Sprite-Alucart_Sworb.png'),
  Curved_Knife: require('../../assets/castlevania/Sprite-Curved_Knife.webp'),
  Discus: require('../../assets/castlevania/Sprite-Discus.webp'),
  Dragon_Water_Whip: require('../../assets/castlevania/Sprite-Dragon_Water_Whip.webp'),
  Fulgur: require('../../assets/castlevania/Sprite-Fulgur.webp'),
  Gale_Force: require('../../assets/castlevania/Sprite-Gale_Force.webp'),
  Guardians_Targe: require('../../assets/castlevania/Sprite-Guardians_Targe.png'),
  Hand_Grenade: require('../../assets/castlevania/Sprite-Hand_Grenade.webp'),
  Hex: require('../../assets/castlevania/Sprite-Hex.webp'),
  Ice_Fang: require('../../assets/castlevania/Sprite-Ice_Fang.webp'),
  Iron_Ball: require('../../assets/castlevania/Sprite-Iron_Ball.webp'),
  Iron_Shield: require('../../assets/castlevania/Sprite-Iron_Shield.webp'),
  Javelin: require('../../assets/castlevania/Sprite-Javelin.webp'),
  Jet_Black_Whip: require('../../assets/castlevania/Sprite-Jet_Black_Whip.webp'),
  Keremet_Bubbles: require('../../assets/castlevania/Sprite-Keremet_Bubbles.webp'),
  Mace: require('../../assets/castlevania/Sprite-Mace.webp'),
  Platinum_Whip: require('../../assets/castlevania/Sprite-Platinum_Whip.webp'),
  Raging_Fire: require('../../assets/castlevania/Sprite-Raging_Fire.webp'),
  Refectio: require('../../assets/castlevania/Sprite-Refectio.webp'),
  Rock_Riot: require('../../assets/castlevania/Sprite-Rock_Riot.webp'),
  Shuriken: require('../../assets/castlevania/Sprite-Shuriken.webp'),
  Sonic_Whip: require('../../assets/castlevania/Sprite-Sonic_Whip.webp'),
  Silver_Revolver: require('../../assets/castlevania/Sprite-Silver_Revolver.png'),
  Star_Flail: require('../../assets/castlevania/Sprite-Star_Flail.webp'),
  Trident: require('../../assets/castlevania/Sprite-Trident.webp'),
  Vanitas_Whip: require('../../assets/castlevania/Sprite-Vanitas_Whip.webp'),
  Vibhuti_Whip: require('../../assets/castlevania/Sprite-Vibhuti_Whip.webp'),
  Wind_Whip: require('../../assets/castlevania/Sprite-Wind_Whip.webp'),
  Wine_Glass: require('../../assets/castlevania/Sprite-Wine_Glass.webp'),
};
